### ISSUE TITLE
404 on Configure field...

### ISSUE THREAD

**Issue by moseisleydk** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#17]
![screen shot 2017-08-30 at 12 11 49](https://user-images.githubusercontent.com/15978685/29869206-57655298-8d82-11e7-9de6-cb84cec4ce44.png)

When pressing Edit JSON HTTP Settings

![screen shot 2017-08-30 at 12 11 41](https://user-images.githubusercontent.com/15978685/29869201-556a1d34-8d82-11e7-8fe8-ccce6e9f976a.png)

**Comment by moseisleydk** [comment]
2017-08-30 13:01:36,736 http-nio-8080-exec-16 ERROR admin 781x311x1 y08s2s 192.168.220.217,127.0.0.1 /secure/admin/EditRequestFieldConfig!default.jspa [c.a.j.config.webwork.JiraActionFactory] Error autowiring Action 'ru.andreymarkelov.atlas.plugins.requestedfiedls.action.EditConfiguration'.
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ru.andreymarkelov.atlas.plugins.requestedfiedls.action.EditConfiguration': Unsatisfied dependency expressed through constructor argument with index 1 of type [ru.andreymarkelov.atlas.plugins.requestedfiedls.manager.PluginData]: : No qualifying bean of type [ru.andreymarkelov.atlas.plugins.requestedfiedls.manager.PluginData] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [ru.andreymarkelov.atlas.plugins.requestedfiedls.manager.PluginData] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1139)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:342)
... 2 filtered
at java.lang.reflect.Method.invoke(Method.java:498)
at com.atlassian.plugin.osgi.spring.DefaultSpringContainerAccessor.createBean(DefaultSpringContainerAccessor.java:97)
at com.atlassian.jira.config.webwork.JiraActionFactory$JiraPluginActionFactory.getActionImpl(JiraActionFactory.java:389)
at webwork.action.factory.PrefixActionFactoryProxy.getActionImpl(PrefixActionFactoryProxy.java:99)
at webwork.action.factory.JspActionFactoryProxy.getActionImpl(JspActionFactoryProxy.java:59)
at webwork.action.factory.CommandActionFactoryProxy.getActionImpl(CommandActionFactoryProxy.java:60)
at com.atlassian.jira.config.webwork.LookupAliasActionFactoryProxy.getActionImpl(LookupAliasActionFactoryProxy.java:61)
at webwork.action.factory.CommandActionFactoryProxy.getActionImpl(CommandActionFactoryProxy.java:51)
at webwork.action.factory.ContextActionFactoryProxy.getActionImpl(ContextActionFactoryProxy.java:36)
at webwork.action.factory.PrepareActionFactoryProxy.getActionImpl(PrepareActionFactoryProxy.java:37)
at com.atlassian.jira.config.webwork.JiraActionFactory$SafeParameterSettingActionFactoryProxy.getActionImpl(JiraActionFactory.java:147)
at webwork.action.factory.ChainingActionFactoryProxy.getActionImpl(ChainingActionFactoryProxy.java:53)
at com.atlassian.jira.config.webwork.JiraActionFactory.getActionImpl(JiraActionFactory.java:301)
... 2 filtered

**Comment by moseisleydk** [comment]
Same for the XML Config :-(

**Comment by AndreyVMarkelov** [comment]
Done in new version. Thank you
