### ISSUE TITLE
IllegalMonitorStateException during initialization of HTTP Feed Custom Fields plugin

### ISSUE THREAD

**Issue by leosjunek** [AndreyVMarkelov/andreymarkelov-atlas-plugins-requestedfields#9]
Hello, 

I'm running JIRA 6.3.4 from WAR, Tomcat 7.0.55 with HTTP Feed Custom Fields plugin.
When starting JIRA, plugin complains about initialization of json-request-custom-field-searcher.

Relevant part of Tomcat log is listed below

Regards, Leos

---

2014-08-21 10:50:54,256 Thread-38 ERROR      [jira.issue.fields.CustomFieldImpl] Exception during searcher initialization of the custom field ru.andreymarkelov.atlas.plugins.requestedfields:json-request-custom-field-searcher:
com.atlassian.cache.CacheException: java.lang.IllegalMonitorStateException: Not reentrant!
        at com.atlassian.cache.memory.DelegatingCache$DelegatingLoadingCache.get(DelegatingCache.java:270)
        at com.atlassian.jira.issue.fields.config.persistence.CachedFieldConfigSchemePersister.getConfigSchemesForCustomField(CachedFieldConfigSchemePersister.java:111)
        at com.atlassian.jira.issue.fields.config.manager.FieldConfigSchemeManagerImpl.getConfigSchemesForField(FieldConfigSchemeManagerImpl.java:84)
        at com.atlassian.jira.issue.fields.CustomFieldImpl.getConfigurationSchemes(CustomFieldImpl.java:1470)
        at ru.andreymarkelov.atlas.plugins.requestedfiedls.SelectTextCustomFieldSearcher.getConfigs(SelectTextCustomFieldSearcher.java:59)
        at ru.andreymarkelov.atlas.plugins.requestedfiedls.SelectTextCustomFieldSearcher.init(SelectTextCustomFieldSearcher.java:143)
        at ru.andreymarkelov.atlas.plugins.requestedfiedls.SelectTextCustomFieldSearcher.init(SelectTextCustomFieldSearcher.java:29)
        at com.atlassian.jira.issue.fields.CustomFieldImpl$CustomFieldSearcherLazyRef.create(CustomFieldImpl.java:2265)
        at com.atlassian.jira.issue.fields.CustomFieldImpl$CustomFieldSearcherLazyRef.create(CustomFieldImpl.java:2233)
        at com.atlassian.util.concurrent.ResettableLazyReference$InternalReference.create(ResettableLazyReference.java:182)
        at com.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:325)
        at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:143)
        at com.atlassian.util.concurrent.LazyReference.get(LazyReference.java:112)
        at com.atlassian.util.concurrent.ResettableLazyReference.get(ResettableLazyReference.java:92)
        at com.atlassian.jira.issue.fields.CustomFieldImpl.getCustomFieldSearcher(CustomFieldImpl.java:1949)
        at com.atlassian.jira.issue.fields.CustomFieldImpl.<init>(CustomFieldImpl.java:275)
        at com.atlassian.jira.issue.fields.DefaultCustomFieldFactory.copyOf(DefaultCustomFieldFactory.java:81)
        at com.atlassian.jira.issue.managers.DefaultCustomFieldManager.getCustomFieldsFromIds(DefaultCustomFieldManager.java:396)
        at com.atlassian.jira.issue.managers.DefaultCustomFieldManager.getCustomFieldObjects(DefaultCustomFieldManager.java:381)
        at com.atlassian.jira.issue.CustomFieldManager$getCustomFieldObjects.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at com.onresolve.scriptrunner.runner.JqlFunctionsManagerImpl.createIndexingCustomField(JqlFunctionsManagerImpl.groovy:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:78)
        at com.onresolve.scriptrunner.runner.JqlFunctionsManagerImpl.this$dist$invoke$1(JqlFunctionsManagerImpl.groovy)
        at com.onresolve.scriptrunner.runner.JqlFunctionsManagerImpl$RegisterJqlFunctions.methodMissing(JqlFunctionsManagerImpl.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:837)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1134)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1087)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
        at com.onresolve.scriptrunner.runner.JqlFunctionsManagerImpl$RegisterJqlFunctions.run(JqlFunctionsManagerImpl.groovy:256)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalMonitorStateException: Not reentrant!
        at com.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:319)
        at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:143)
        at com.atlassian.util.concurrent.LazyReference.get(LazyReference.java:112)
        at com.atlassian.util.concurrent.ResettableLazyReference.get(ResettableLazyReference.java:92)
        at com.atlassian.jira.issue.fields.CustomFieldImpl.getCustomFieldSearcher(CustomFieldImpl.java:1949)
        at com.atlassian.jira.issue.fields.CustomFieldImpl.<init>(CustomFieldImpl.java:275)
        at com.atlassian.jira.issue.fields.DefaultCustomFieldFactory.copyOf(DefaultCustomFieldFactory.java:81)
        at com.atlassian.jira.issue.managers.DefaultCustomFieldManager.getCustomFieldObject(DefaultCustomFieldManager.java:328)
        at com.atlassian.jira.issue.managers.DefaultCustomFieldManager.getCustomFieldObject(DefaultCustomFieldManager.java:339)
        at com.atlassian.jira.issue.fields.DefaultFieldManager.getCustomField(DefaultFieldManager.java:609)
        at com.atlassian.jira.issue.fields.DefaultFieldManager.getField(DefaultFieldManager.java:141)
        at com.atlassian.jira.issue.fields.config.persistence.CachedFieldConfigSchemePersister$FieldConfigSchemeByFieldCacheLoader.load(CachedFieldConfigSchemePersister.java:216)
        at com.atlassian.jira.issue.fields.config.persistence.CachedFieldConfigSchemePersister$FieldConfigSchemeByFieldCacheLoader.load(CachedFieldConfigSchemePersister.java:211)
        at com.atlassian.cache.memory.MemoryCacheManager$3$1.load(MemoryCacheManager.java:132)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3573)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3970)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4834)
        at com.atlassian.cache.memory.DelegatingCache$DelegatingLoadingCache.get(DelegatingCache.java:264)
        ... 48 more

**Comment by ixznagy** [comment]
We receive the same exception on JIRA 6.4.6 and 6.4.12
